blank_issues_enabled: false
contact_links:
  - name: ⚠️ Application issue
    url: https://github.com/suwayomi/tachiyomi-extension/issues/new/choose
    about: Issues and requests about the app itself should be opened in the app repository instead
  - name: 🖥️ Suwayomi website
    url: https://suwayomi.org/
    about: Guides, troubleshooting, and answers to common questions
